<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error occured, try again later…' => 'خطایی هنگام آپلود رخ داده است. لطفا بعدا ',
    'Are you sure you want to delete this item?' => 'آیا می خواهید این عکس را حذف نمایید؟',
    'Attachments' => 'فایل های ضمیمه',
    'Create' => 'ایجاد',
    'Create Attachment' => 'ایجاد فایل ضمیمه',
    'Delete' => 'حذف',
    'Error saving file' => 'خطای ذخیره سازی عکس',
    'File types' => 'نوع فایل',
    'ID' => 'شناسه',
    'Image size' => 'اندازه عکس',
    'Max. file size' => 'بیشترین حجم فایل',
    'Max. height' => 'بیشترین ارتفاع',
    'Max. size of image' => 'بیشترین حجم عکس',
    'Max. width' => 'بیشترین عرض',
    'Min. height' => 'کمترین ارتفاع',
    'Min. size of image' => 'کمترین حجم عکس',
    'Min. width' => 'کمترین عرض',
    'Publish' => 'انتشار',
    'Reset' => 'بازنشانی',
    'Search' => 'جستجو',
    'Stat' => 'آمار',
    'Title' => 'عنوان',
    'Update' => 'ویرایش',
    'Update {modelClass}: ' => 'ویرایش فایل ضمیمه',
    'attachment id' => 'شناسه فایل',
    'visit count' => 'تعداد بازدید',
];
